Refactor modal javascript in modal component
oslokommune/styleguide pull request #289
Opened 2022-06-09 13:40 UTC by cristain7

Det funker ikke i kontekst av styleguide, på grunn av scope av document inne frames, men det funker i kontekst av prosjekt

2022-06-09 13:53 UTC, larsboldt requested changes

2022-06-09 13:53 UTC, larsboldt commented on src/components/modal/modal.js
> +    const triggers = document.querySelectorAll(`[aria-controls=${filterPanel.getAttribute("id")}]`);
filterpanel?

2022-06-10 06:25 UTC, larsboldt approved these changes

2022-06-12 13:20 UTC, kbergha approved these changes

2022-06-13 07:08 UTC, jeanettelandoyaune approved these changes

2022-06-13 07:55 UTC, closed without merging