io-397 expose resize as method on map
oslokommune/styleguide pull request #327
Opened 2022-09-08 11:58 UTC by larsboldt

2022-09-08 11:59 UTC, cristain7 approved these changes

2022-09-08 13:44 UTC, jeanettelandoyaune approved these changes

2022-09-08 13:45 UTC, kbergha requested changes
Mangler litt på dokumentasjon av resize i o-store gule boks med teknisk info.

2022-09-09 07:28 UTC, kbergha approved these changes

2022-09-09 07:43 UTC, merged