Io 548
oslokommune/styleguide pull request #339
Opened 2022-10-13 14:00 UTC by cristain7

2022-10-19 13:23 UTC, jeanettelandoyaune approved these changes

2022-10-20 10:43 UTC, larsboldt requested changes
version change should be its own commit

2022-10-20 10:43 UTC, larsboldt commented on package.json
> +  "version": "0.99.91",
version change should be its own commit

2022-10-20 10:43 UTC, larsboldt commented on src/components/_index.scss
> +@use "links/content_link/content_link";
why name change?

2022-10-20 11:07 UTC, cristain7 commented on src/components/_index.scss
> +@use "links/content_link/content_link";
Forgot to delete this merge request in favor of https://github.com/oslokommune/styleguide_devtools/pull/47

2022-10-20 11:08 UTC, cristain7 commented
Not merged

2022-10-20 11:08 UTC, closed without merging