remove states and rename blue-contrast to blue-hover
oslokommune/styleguide pull request #340
Opened 2022-10-17 13:18 UTC by jeanettelandoyaune

Relatert til PR i devtools

2022-10-20 07:35 UTC, cristain7 commented on src/system/_states.scss
> -$active: colors.$blue-contrast;
Bør ikke denne filen også fjernes?

2022-10-20 10:54 UTC, larsboldt requested changes

2023-01-03 14:26 UTC, cristain7 requested changes
Det finnes flere @use "system/states"; som ikke eksisterer nå

2023-01-03 14:26 UTC, cristain7 commented on src/components/form/input/_mixins.scss
>      color: states.$disabled-text;
$colors.$gray

2023-01-03 14:26 UTC, cristain7 commented on src/components/pagination/pagination.scss
> +      color: states.$active;
colors.$blue-state;

2023-01-03 14:26 UTC, cristain7 commented on src/components/pagination/pagination.scss
> +        background: states.$hover !important;
colors.$blue-state;

2023-01-03 14:26 UTC, cristain7 commented on src/components/pagination/pagination.scss
> +        color: states.$hover-text !important;
colors.$blue-state;

2023-01-03 14:26 UTC, cristain7 commented on src/components/tabs/tabs.scss
> +      border-bottom: 2px solid states.$hover;
colors.$blue-state;

2023-01-03 14:26 UTC, cristain7 commented on src/components/tabs/tabs.scss
> +      color: states.$hover;
colors.$blue-state;

2023-01-03 14:26 UTC, cristain7 commented on src/components/breadcrumb/breadcrumb.scss
>  @use "system/states";
Fjern

2023-01-03 14:26 UTC, cristain7 commented on src/components/button/button.scss
> +@use "system/states";
Fjern

2023-01-03 14:26 UTC, cristain7 commented on src/components/cards/portrait_card/portrait_card.scss
> +@use "system/states";
Fjern

2023-01-03 14:26 UTC, cristain7 commented on src/components/form/date/date.scss
> +@use "system/states";
Fjern

2023-01-03 14:26 UTC, cristain7 commented on src/components/form/search/search.scss
> +@use "system/states";
Fjern

2023-01-06 10:07 UTC, jeanettelandoyaune commented on src/components/form/input/_mixins.scss
>      color: states.$disabled-text;
Jeg trodde vi skulle beholde den statesfilen men fjerne "states" fra styleguiden slik at hvis vi endrer statefarge så skal man ikke trenge å gjøre det overalt?

2023-01-06 10:22 UTC, cristain7 commented on src/components/form/input/_mixins.scss
>      color: states.$disabled-text;
skjønner, jeg se på linje 69 og 71 som fjern states, fordi de er bort i states fil, jeg forstår nå :)

2023-01-06 10:22 UTC, cristain7 approved these changes

2023-01-12 07:58 UTC, larsboldt approved these changes

2023-01-19 13:03 UTC, kbergha approved these changes

2023-01-20 07:48 UTC, merged