Io 614 Remove aria-hidden from maps
oslokommune/styleguide pull request #343
Opened 2022-11-09 14:00 UTC by cristain7

2022-11-10 17:14 UTC, kbergha commented
Why are there two PRs with the same code and different IO-number?

2022-11-10 17:15 UTC, kbergha requested changes
Why are there two PRs with the same code and different IO-numbers?

2022-11-10 22:08 UTC, cristain7 commented
This is the correct branch, the other (io-607) is the name of the branch for the changes in CorePublish and I created it by mistake here, and should have removed it before you reviewed it. So this is the branch that should be merged to match the Trello card 
https://trello.com/c/QHvTxjoB/614-fjern-aria-hidden-fra-kart

2022-11-10 22:22 UTC, kbergha approved these changes

2022-11-16 09:01 UTC, larsboldt approved these changes

2022-11-16 09:07 UTC, merged