Make menu button text available to screen readers on mobile
oslokommune/styleguide pull request #344
Opened 2022-11-10 13:23 UTC by cristain7

2022-11-10 17:18 UTC, kbergha requested changes
What's up with the map-stuff??
That code is not merged, and should not be available in this branch...

2022-11-10 22:16 UTC, cristain7 commented
> 

I  created the code based on the wrong branch instead of main, now it is fixed

2022-11-10 22:24 UTC, kbergha approved these changes

2022-11-16 09:02 UTC, larsboldt approved these changes

2022-11-16 09:08 UTC, merged