Io 656 Add translation to image carousel with i18n object
oslokommune/styleguide pull request #358
Opened 2022-12-01 10:39 UTC by cristain7

2022-12-01 11:11 UTC, jeanettelandoyaune approved these changes

2022-12-01 12:55 UTC, kbergha commented on src/components/image_carousel/image_carousel.vue
> +          previousBtn: "Show previous image",
Explicit "Button" please, not "Btn".

Should be fixed in pagination as well if you're willing ;)

2022-12-01 12:56 UTC, kbergha requested changes
See code comment about btn vs button.

2022-12-02 06:34 UTC, kbergha approved these changes

2022-12-02 06:47 UTC, merged