Added infobox collapsible variant
oslokommune/styleguide pull request #368
Opened 2023-01-19 12:19 UTC by cristain7

2023-01-19 13:08 UTC, larsboldt requested changes

2023-01-19 13:08 UTC, larsboldt commented on src/components/collapsible/collapsible.js
> +  const elementTarget = document.querySelector(".osg-infobox__icon-trigger") ? e.currentTarget : e.target;
You can not put component specific code in collapsible helper

2023-01-19 13:08 UTC, larsboldt commented on src/components/collapsible/collapsible.js
> +    if (document.querySelector(".osg-infobox__icon-trigger")) {
No - collapsible does not want to know about infobox

2023-01-19 13:08 UTC, larsboldt commented on src/components/collapsible/collapsible.js
> +function toggleIcon(e) {
No - collapsible does not care about icons... use events

2023-01-20 07:59 UTC, jeanettelandoyaune approved these changes

2023-01-20 08:54 UTC, larsboldt requested changes

2023-01-20 08:54 UTC, larsboldt commented on src/components/infobox/infobox.html
> +                  <h3>
h3 and h2 nested in next sibling - the other way around although different roots?

2023-01-20 08:54 UTC, larsboldt commented on src/components/infobox/infobox.scss
> +    font-size: 1.5em;
This should probably be rem instead of em - assuming you copied this from styleguide devtools which is abit old code

2023-01-20 08:54 UTC, larsboldt commented on src/components/infobox/infobox.scss
> +    top: 0px;
instead of top and padding-top, can top be 1rem?

2023-01-20 08:57 UTC, cristain7 commented on src/components/infobox/infobox.html
> +                  <h3>
Good point, didn't look into the content of the collapsible, I just copied the other infoboxes text. Will fix

2023-01-20 09:00 UTC, cristain7 commented on src/components/infobox/infobox.scss
> +    top: 0px;
I can't because this is related to the position of the icon inside the round "button". Top would move the blue round background down and padding-top would move the chevron icon down.

2023-01-20 09:06 UTC, cristain7 commented on src/components/infobox/infobox.scss
> +    font-size: 1.5em;
Yes, that is what happened!

2023-01-20 10:50 UTC, larsboldt approved these changes

2023-01-23 08:46 UTC, merged