Io 701 - made i18n required and removed unused props image caroussel
oslokommune/styleguide pull request #380
Opened 2023-02-15 09:02 UTC by jeanettelandoyaune

2023-02-15 12:07 UTC, larsboldt requested changes

2023-02-15 12:07 UTC, larsboldt commented on src/components/image_carousel/image_carousel.vue
>        default: () => {
Trenger ingen default når den er required

2023-02-16 07:36 UTC, jeanettelandoyaune commented on src/components/image_carousel/image_carousel.vue
>        default: () => {
good point! fixd!

2023-02-19 21:25 UTC, kbergha approved these changes

2023-02-20 12:13 UTC, closed without merging