Io 811
oslokommune/styleguide pull request #390
Opened 2023-02-28 13:40 UTC by cristain7

2023-02-28 14:32 UTC, jeanettelandoyaune approved these changes

2023-03-01 10:27 UTC, larsboldt requested changes

2023-03-01 10:27 UTC, larsboldt commented on src/components/status_message/status_message.html
>            <p class="osg-status-message__small-text">Lorem Ipsum is simply dummy text</p>
this should be named something related to what is expected to put here - e.g date

2023-03-01 10:42 UTC, cristain7 commented on src/components/status_message/status_message.html
>            <p class="osg-status-message__small-text">Lorem Ipsum is simply dummy text</p>
yes, I agree :)

2023-03-01 10:51 UTC, larsboldt approved these changes

2023-03-01 10:59 UTC, merged