removed visited state and changed from purple to blue
oslokommune/styleguide pull request #396
Opened 2023-03-07 10:04 UTC by jeanettelandoyaune

2023-03-07 10:21 UTC, larsboldt requested changes
Du skulle bare endre farge på visited state - ikke fjerne staten

2023-03-07 14:24 UTC, larsboldt commented on src/components/links/link/_mixins.scss
> +    color: states.$visited;
Har du sjekket at fjerning av important ikke borker noe?

2023-03-08 08:26 UTC, jeanettelandoyaune commented on src/components/links/link/_mixins.scss
> +    color: states.$visited;
copy paste gone wrong!

2023-03-09 08:01 UTC, larsboldt commented on src/components/links/link/_mixins.scss
> +    color: states.$visited!important;
Mangler vel en space mellom variable og !

2023-03-09 10:09 UTC, kbergha approved these changes

2023-03-09 10:42 UTC, larsboldt approved these changes

2023-03-10 12:21 UTC, closed without merging