Update status message markup in the map component
oslokommune/styleguide pull request #400
Opened 2023-03-16 12:25 UTC by cristain7

2023-03-18 07:58 UTC, kbergha approved these changes

2023-03-18 08:14 UTC, kbergha requested changes
I think we agreed to start the changelog?
Maybe we should do a discussion on format / detail level.

2023-03-30 09:39 UTC, jeanettelandoyaune approved these changes

2023-03-30 10:03 UTC, kbergha approved these changes

2023-04-12 12:07 UTC, cristain7 commented
Merged into main

2023-04-12 12:07 UTC, closed without merging