io-586 added do not track and sandbox example and information to video
oslokommune/styleguide pull request #410
Opened 2023-04-05 08:59 UTC by jeanettelandoyaune

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-sandbox
Lager bare PR på denne men må tas i fellesskap ang hvilke attributter som er mest relevante å ta i bruk.

2023-04-14 12:58 UTC, larsboldt approved these changes

2023-04-14 12:58 UTC, larsboldt requested changes
Mangler changelog entry

2023-04-17 10:47 UTC, kbergha approved these changes
Men: Det Lars sa, pluss husk å holde miniforedrag om sandbox til oss (ta det på et utviklermøte)...

2023-04-17 12:37 UTC, jeanettelandoyaune commented
> Mangler changelog entry

oppdatert!

2023-04-18 07:23 UTC, cristain7 approved these changes

2023-04-24 07:08 UTC, larsboldt commented on CHANGELOG.md
> +- added do not track and sandbox example and information to video component
Stor bokstav i Added

2023-05-03 08:13 UTC, larsboldt approved these changes

2023-05-08 09:20 UTC, jeanettelandoyaune commented
rebase og merget

2023-05-08 09:20 UTC, closed without merging