Add icon breakpoint classes and documentation accordingly
oslokommune/styleguide pull request #411
Opened 2023-04-12 09:07 UTC by cristain7

2023-04-12 12:00 UTC, larsboldt approved these changes

2023-04-12 12:44 UTC, jeanettelandoyaune approved these changes

2023-04-14 12:59 UTC, larsboldt requested changes
Mangler changelog entry

2023-04-17 09:16 UTC, larsboldt approved these changes

2023-04-17 10:42 UTC, kbergha approved these changes

2023-04-18 08:54 UTC, closed without merging

2023-04-18 08:54 UTC, cristain7 commented
merged into main