added details to states in link and breadcrumb component
oslokommune/styleguide pull request #413
Opened 2023-04-25 08:27 UTC by jeanettelandoyaune

2023-04-26 05:14 UTC, kbergha approved these changes

2023-04-26 08:46 UTC, cristain7 approved these changes

2023-04-26 08:50 UTC, larsboldt requested changes
Mangler changelog entry...

2023-04-26 08:50 UTC, larsboldt commented on src/components/breadcrumb/breadcrumb.html
> +            <a class="osg-breadcrumb__link--visited" href="javascript:void(0)">Visited</a>
mangler link klassen på alle anchors - kan ikke kun benytte modifier uten klassen det er modifier på

2023-04-27 08:35 UTC, larsboldt requested changes

2023-04-27 08:35 UTC, larsboldt commented on src/components/breadcrumb/breadcrumb.html
> +            <a class="osg-breadcrumb__active osg-breadcrumb__link osg-breadcrumb__link--active" href="javascript:void(0)">Active</a>
breadcrumb_active skal ikke på en lenke så den må bort

2023-05-03 08:14 UTC, larsboldt approved these changes

2023-05-08 09:32 UTC, closed without merging