Fix position of icon arrow in select component
oslokommune/styleguide pull request #415
Opened 2023-04-25 10:01 UTC by cristain7

2023-04-26 08:56 UTC, jeanettelandoyaune approved these changes

2023-04-26 09:01 UTC, larsboldt requested changes

2023-04-26 09:01 UTC, larsboldt commented on CHANGELOG.md
> +## [unreleased]
Stor U i Unreleased

2023-04-27 08:37 UTC, larsboldt approved these changes

2023-04-27 13:08 UTC, kbergha approved these changes

2023-04-27 20:00 UTC, merged