Io 162 - radiobutton bold on checked
oslokommune/styleguide pull request #421
Opened 2023-05-19 13:22 UTC by jeanettelandoyaune

2023-05-19 20:04 UTC, cristain7 reviewed
Det er mulig å endre det med CSS, med en liten endring i HTML-strukturen. 
Jeg tror det er mer effektivt enn å bruke javascript:

Hvis .osg-radio__label er sibling av input, kan du enkelt endre det :)

`
<span class="osg-radio__input">
    <input type="radio" name="radio-11" />
    <span class="osg-radio__control"></span>
    <span class="osg-radio__label">Text</span>
 </span>
 `

2023-05-23 12:58 UTC, jeanettelandoyaune commented on src/components/form/radio/radio.scss
> +  input[type="radio"]:checked ~ .osg-radio__label {
good point! fixed :D

2023-05-23 13:12 UTC, cristain7 commented on src/components/form/radio/radio.scss
> +    @extend %osg-text--weight-medium;
Alle @extends sammen please!

2023-05-23 13:24 UTC, cristain7 approved these changes

2023-05-24 08:54 UTC, larsboldt requested changes

2023-05-24 08:54 UTC, larsboldt commented on src/components/form/radio/radio.scss
> +    line-height: 1.5 !important;
1.5 what?

2023-05-24 08:54 UTC, larsboldt commented on src/components/form/radio/radio.vue
> +  </span>
noe rart med indentering

2023-05-24 08:54 UTC, larsboldt commented on CHANGELOG.md
> +- radiobutton gets fontweight medium when checked - Breaking change!
Stor bokstav i radiobutton

2023-05-26 09:20 UTC, kbergha approved these changes

2023-05-26 09:23 UTC, merged